title: Linux Oriented Life.
description: Uğur KAZDAL Blog on Technology
author: Uğur Kazdal
github: https://github.com/uurtech
about: I'm a Linux Ent. Who loves PHP, Python, Go and So.
google_analytics: UA-133420208-1
avatar_url: /static/img/ugur-kazdal.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/ugurkazdal"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/ugur-kazdal-88086a152/"
    - icon: fa-github
      link: "https://github.com/uurtech"

share:
  twitter_username: ugurkazdal

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://ugurkazdal.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['production']
